@client_secret=PzotcrvZRF9BHCKcUxdKfHWlIPECG49k
@refresh_token=eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmNmU3NjM3Zi1lNzllLTQ4YzAtOWIyNC0yY2QyZTFhNDczOTAifQ.eyJleHAiOjE3Mzg5NzM0MjgsImlhdCI6MTczODk3MTYyOCwianRpIjoiM2Y0NzhkNzgtMzUxNi00NjNlLWJiM2UtMjE3Yjk5YWExMmRmIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDoxODA4MC9yZWFsbXMvZXZlbnRseSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTgwODAvcmVhbG1zL2V2ZW50bHkiLCJzdWIiOiI3MjFmMjEzOC05ZmIwLTQ0NDUtYTI3Yi0yNjYxOTc0NzNjZTIiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoiZXZlbnRseS1wdWJsaWMtY2xpZW50Iiwic2lkIjoiNWZlMjhmNTktNGU5Ny00YTZjLWE2YTYtZjlkMzQ3MmQxNDAyIiwic2NvcGUiOiJvcGVuaWQgd2ViLW9yaWdpbnMgYWNyIHJvbGVzIGJhc2ljIGVtYWlsIHByb2ZpbGUifQ._nw-8O16wFpoBLRkeCv6so4olyEqo2SCQsl6_yt6ck_oLLSrIldHxGH0Q5AxGkJhnwhzVGJ5UDoqlOLOeeg3Fg

###
# group: AccessToken
POST {{keycloak_url}}/realms/evently/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=evently-public-client&scope=email%20openid&username=test@test.com&password=123456

###
# group: RefreshToken
POST {{keycloak_url}}/realms/evently/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&client_id=evently-public-client&refresh_token={{refresh_token}}


###
# group: ClientCredentials
POST {{keycloak_url}}/realms/evently/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=evently-confidential-client&client_secret={{client_secret}}&scope=openid

###
# group: Health
GET {{keycloak_url}}/health